routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();



Route::middleware(['auth'])->group(function () {
    Route::get('profile', 'HomeController@profile')->name('profile');
    Route::get('/', 'HomeController@index')->name('home');
    Route::post('/', 'HomeController@result');
    Route::resource('questions', 'QuestionController');
    Route::resource('codes', 'CodeController');
    Route::resource('majors', 'MajorController');
});

app/Code.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Code extends Model
{
    protected $table = 'codes';

    public function questions()
    {
        return $this->hasMany('App\Question');
    }

    public function majors()
    {
        return $this->hasMany('App\Major');
    }
}

app/Http/Controllers/CodeController.php
<?php

namespace App\Http\Controllers;

use App\Code;
use Illuminate\Http\Request;

class CodeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $codes = Code::all();
        return view('codes.index', ['codes' => $codes]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('codes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $code = new Code;
        $code->title = $request->get('title');
        $code->description = $request->get('description');
        $code->save();

        flash('Code was successfully created.')->success();

        return redirect()->route('codes.create');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Code  $code
     * @return \Illuminate\Http\Response
     */
    public function show(Code $code)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Code  $code
     * @return \Illuminate\Http\Response
     */
    public function edit(Code $code)
    {
        return view('codes.edit', ['code' => $code]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Code  $code
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Code $code)
    {
        $code->title = $request->get('title');
        $code->description = $request->get('description');
        $code->save();

        flash('Code was successfully updated.')->success();

        return redirect()->route('codes.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Code $code
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Code $code)
    {
        $code->delete();

        flash('Code was successfully deleted.')->success();

        return redirect()->route('codes.index');
    }
}

resources/views/codes/create.blade.php
@extends('layouts.app')

@section('title')
    Tạo câu hỏi
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 col-md-offset-2">
            @include('flash::message')
            @if ($errors->any())
                <div class="alert alert-danger alert-dismissible fade in" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="card">
                <div class="card-header">
                    Tạo tính cách theo John Holland
                </div>

                <div class="card-body">
                    <form class="form-horizontal" method="POST" action="{{ route('codes.store') }}">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                            <label for="title" class="control-label">Code:</label>

                                <input id="title" value="{{ old('title')}}" class="form-control" name="title" required>

                                @if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                        </div>

                        <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                            <label for="description" class="control-label">Mô tả:</label>

                            <textarea id="description" rows="10" class="form-control" name="description">{{ old
                                ('description')}}</textarea>

                            @if ($errors->has('description'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                            @endif
                        </div>

                        <div class="form-group">
                            {{--<div class="col-md-6">--}}
                                <button type="submit" class="btn btn-primary">
                                    Tạo
                                </button>

                            <a href="{{ route('codes.index') }}" class="btn btn-danger btn-xs">
                                Trở về
                            </a>
                            {{--</div>--}}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/codes/edit.blade.php
@extends('layouts.app')

@section('title')
    Sửa câu hỏi
@endsection

@section('content')
<div class="container">

    <div class="row justify-content-center">
        <div class="col-md-8 col-md-offset-2">
            @include('flash::message')
            @if ($errors->any())
                <div class="alert alert-danger alert-dismissible fade in" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="card">
                <div class="card-header">
                    Sửa câu hỏi
                </div>

                <div class="card-body">
                    <form class="form-horizontal" method="POST" action="{{ route('codes.update', ['user' =>
                    $code->id]) }}">
                        {{ csrf_field() }} {{ method_field('PUT') }}

                        <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                            <label for="title" class="control-label">Code:</label>

                            {{--<div class="col-md-6">--}}
                                <input id="title" value="{{ old('title',
                                $code->title)
                                }}" class="form-control" name="title" required>
                                @if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            {{--</div>--}}
                        </div>

                        <div class="form-group {{ $errors->has('description') ? ' has-error' : '' }}">
                            <label for="code_id" class="control-label">Mô tả</label>

                            <textarea id="description" rows="10" class="form-control" name="description" required>{{
                            old('description',
                                $code->description)
                                }}</textarea>
                            @if ($errors->has('description'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                            @endif
                        </div>

                        <div class="form-group">
                            {{--<div class="col-md-6 col-md-offset-4">--}}
                                <button type="submit" class="btn btn-primary">
                                    Cập nhật
                                </button>

                                <a href="{{ route('codes.index') }}" class="btn btn-danger btn-xs pull-right">
                                    Trở về
                                </a>
                            {{--</div>--}}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/codes/index.blade.php
@extends('layouts.app')

@section('title')
    Bộ câu hỏi John Holland
@endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header clearfix">
                        <h5 class="float-left" style="margin: 0;line-height: 26px;">
                            Danh sách mã John Holland
                        </h5>
                        <a href="{{ route('codes.create') }}" class="btn btn-primary btn-sm float-right">
                            <span class="glyphicon glyphicon-plus-sign"></span> Tạo mới
                        </a>
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif

                            <table class="table table-condensed table-hover">
                                <thead class="thead-inverse">
                                <tr>
                                    <th>ID</th>
                                    <th>Tiêu đề</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                @forelse($codes as $code)
                                    <tr>
                                        <td scope="row">{{ $code->id }}</td>

                                        <td>
                                            {{ $code->title }}
                                        </td>

                                            <td style="text-align: center">

                                                <a class="btn btn-sm btn-primary" href="{{ route('codes.edit',
                                                $code->id) }}">
                                                    Sửa
                                                </a>

                                                <a class="btn btn-danger btn-sm" href="{{ route('codes.destroy',
                                                ['code' =>$code->id]) }}" onclick="event.preventDefault();document
                                                        .getElementById('logout-form{{$code->id}}').submit();">
                                                    Xóa
                                                </a>

                                                <form id="logout-form{{$code->id}}" action="{{ route('logout') }}" method="POST" style="display: none;">
                                                    @csrf
                                                    {{ method_field('DELETE') }}
                                                </form>
                                            </td>

                                    </tr>
                                @empty
                                    <tr>
                                        <p class="text-danger">Không có câu hỏi nào</p>
                                    </tr>
                                @endforelse

                                </tbody>
                            </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection