routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();



Route::middleware(['auth'])->group(function () {
    Route::get('profile', 'HomeController@profile')->name('profile');
    Route::get('/', 'HomeController@index')->name('home');
    Route::post('/', 'HomeController@result');
    Route::resource('questions', 'QuestionController');
    Route::resource('codes', 'CodeController');
    Route::resource('majors', 'MajorController');
});

app/Major.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Major extends Model
{
    protected $table = 'majors';

    public function code()
    {
        return $this->belongsTo('App\Code');
    }
}

app/Http/Controllers/MajorController.php
<?php

namespace App\Http\Controllers;

use App\Code;
use App\Major;
use Illuminate\Http\Request;

class MajorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $majors = Major::orderBy('id', 'desc')->get();
        return view('majors.index', ['majors' => $majors]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $codes = Code::all();
        return view('majors.create', ['codes' => $codes]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $major = new Major;
        $major->title = $request->get('title');
        $major->code_id = $request->get('code_id');
        $major->save();

        flash('Major was successfully created.')->success();

        return redirect()->route('majors.create');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Major  $major
     * @return \Illuminate\Http\Response
     */
    public function show(Major $major)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Major  $major
     * @return \Illuminate\Http\Response
     */
    public function edit(Major $major)
    {
        $codes = Code::all();
        return view('majors.edit', ['codes' => $codes, 'major' => $major]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Major  $major
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Major $major)
    {
        $major->title = $request->get('title');
        $major->code_id = $request->get('code_id');
        $major->save();

        flash('Major was successfully updated.')->success();

        return redirect()->route('majors.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Major $major
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Major $major)
    {
        $major->delete();

        flash('Major was successfully deleted.')->success();

        return redirect()->route('majors.index');
    }
}

resources/views/majors/create.blade.php
@extends('layouts.app')

@section('title')
    Tạo câu hỏi
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 col-md-offset-2">
            @include('flash::message')
            @if ($errors->any())
                <div class="alert alert-danger alert-dismissible fade in" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="card">
                <div class="card-header">
                    Tạo ngành học
                </div>

                <div class="card-body">
                    <form class="form-horizontal" method="POST" action="{{ route('majors.store') }}">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                            <label for="title" class="control-label">Ngành học</label>

                            {{--<div class="col-md-6">--}}
                                <textarea id="title" rows="3" class="form-control" name="title" required>{{ old
                                ('title')}}</textarea>

                                @if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            {{--</div>--}}
                        </div>

                        <div class="form-group">
                            <label for="code_id" class="control-label">John Holland Code</label>

                            {{--<div class="col-md-3">--}}
                                <select name="code_id" class="form-control">
                                    @foreach ($codes as $key => $code)
                                        <option value="{{ $code->id }}">{{ $code->title }}</option>
                                    @endforeach
                                </select>
                            {{--</div>--}}
                        </div>

                        <div class="form-group">
                            {{--<div class="col-md-6">--}}
                                <button type="submit" class="btn btn-primary">
                                    Tạo
                                </button>

                            <a href="{{ route('majors.index') }}" class="btn btn-danger btn-xs">
                                Trở về
                            </a>
                            {{--</div>--}}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/majors/edit.blade.php
@extends('layouts.app')

@section('title')
    Sửa câu hỏi
@endsection

@section('content')
<div class="container">

    <div class="row justify-content-center">
        <div class="col-md-8 col-md-offset-2">
            @include('flash::message')
            @if ($errors->any())
                <div class="alert alert-danger alert-dismissible fade in" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="card">
                <div class="card-header">
                    Sửa ngành học
                </div>

                <div class="card-body">
                    <form class="form-horizontal" method="POST" action="{{ route('majors.update', ['user' =>
                    $major->id]) }}">
                        {{ csrf_field() }} {{ method_field('PUT') }}

                        <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                            <label for="title" class="control-label">Câu hỏi:</label>

                            {{--<div class="col-md-6">--}}
                                <textarea id="title" rows="3" class="form-control" name="title" required>{{ old('title',
                                $major->title)
                                }}</textarea>
                                @if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            {{--</div>--}}
                        </div>

                        <div class="form-group">
                            <label for="code_id" class="control-label">John Holland Code</label>

                            {{--<div class="col-md-3">--}}
                                @if(!$codes->isEmpty())
                                <select name="code_id" class="form-control">
                                    @foreach ($codes as $key => $code)
                                        <option value="{{ $code->id }}" {{ old('code_id', $major->code_id) ==
                                        $code->id ?
                                        'selected' :
                                         ''
                                        }}>{{ $code->title }}</option>
                                    @endforeach
                                </select>
                                @endif
                            {{--</div>--}}
                        </div>

                        <div class="form-group">
                            {{--<div class="col-md-6 col-md-offset-4">--}}
                                <button type="submit" class="btn btn-primary">
                                    Cập nhật
                                </button>

                                <a href="{{ route('majors.index') }}" class="btn btn-danger btn-xs pull-right">
                                    Trở về
                                </a>
                            {{--</div>--}}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/majors/index.blade.php
@extends('layouts.app')

@section('title')
    Bộ câu hỏi John Holland
@endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header clearfix">
                        <h5 class="float-left" style="margin: 0;line-height: 26px;">
                            Danh sách ngành học phân loại theo mã John Holland
                        </h5>
                        <a href="{{ route('majors.create') }}" class="btn btn-primary btn-sm float-right">
                            <span class="glyphicon glyphicon-plus-sign"></span> Tạo mới
                        </a>
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif

                            <table class="table table-condensed table-hover">
                                {{--<thead class="thead-inverse">--}}
                                {{--<tr>--}}
                                    {{--<th>ID</th>--}}
                                    {{--<th>Tiêu đề</th>--}}
                                    {{--<th></th>--}}
                                {{--</tr>--}}
                                {{--</thead>--}}
                                <tbody>
                                @forelse($majors as $major)
                                    <tr>
                                        <td scope="row">{{ $major->id }}</td>

                                        <td>
                                            {{ $major->title }}
                                        </td>
                                        <td>
                                            {{ $major->code->title }}
                                        </td>


                                            <td style="text-align: center">

                                                <a class="btn btn-sm btn-primary" href="{{ route('majors.edit',
                                                $major->id) }}">
                                                    Sửa
                                                </a>

                                                <a class="btn btn-danger btn-sm" href="#" onclick="event
                                                        .preventDefault();document
                                                        .getElementById('logout-form{{$major->id}}').submit();">
                                                    Xóa
                                                </a>

                                                <form id="logout-form{{$major->id}}" action="{{ route('majors.destroy', ['major' =>$major->id]) }}"
                                                      method="POST"
                                                      style="display: none;">
                                                    @csrf
                                                    {{ method_field('DELETE') }}
                                                </form>
                                            </td>

                                    </tr>
                                @empty
                                    <tr>
                                        <p class="text-danger">Không có ngành học nào</p>
                                    </tr>
                                @endforelse

                                </tbody>
                            </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection